/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.3.1-20-g07fb6d391c"
#endif /* AVUTIL_FFVERSION_H */
